version: "3.7"

services:

    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment:
        - APP_NAME=MyFlaskApp
        expose:
        - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
        - "81:80"

    mariadb:
        image: mariadb:10.2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vorlesungsplaner
            MYSQL_USER: user
            MYSQL_PASSWORD: changeMe
        restart: on-failure
        ports:
            - "33006:3306"
        expose: 
            - "3306"
